kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: scminecraft
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: managed
reclaimPolicy: Retain
mountOptions:
  - debug
volumeBindingMode: Immediate
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  ports:
    - port: 80
      protocol: TCP
      name: tcp80
      targetPort: 25565
    - port: 443
      name: ssl
      protocol: TCP
      targetPort: 25575
    - port: 25565
      name: http
      targetPort: 25565
    - port: 25575
      name: https
      targetPort: 25575
  selector:
    pod-name: minecraft
  type: LoadBalancer
  sessionAffinity: ClientIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
spec:
  serviceName: "minecraft"
  replicas: 3
  selector:
    matchLabels:
      pod-name: minecraft
  template:
    metadata:
      labels:
        pod-name: minecraft
    spec:
      hostname: minecraft
      containers:
        - name: minecraft
          image: openhack/minecraft-server:2.0
          volumeMounts:
            - mountPath: /data
              name: mcdata
          ports:
            - containerPort: 25565
            - containerPort: 25575
          env:
            - name: "EULA"
              value: "TRUE"
  volumeClaimTemplates:
    - metadata:
        name: mcdata
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: scminecraft
        resources:
          requests:
            storage: 5Gi
